class Autogenerated {
  String type;
  String name;
  String database;
  List<Data> data;

  Autogenerated({this.type, this.name, this.database, this.data});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    type = json['type'];
    name = json['name'];
    database = json['database'];
    if (json['data'] != null) {
      data = new List<Data>();
      json['data'].forEach((v) {
        data.add(new Data.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['type'] = this.type;
    data['name'] = this.name;
    data['database'] = this.database;
    if (this.data != null) {
      data['data'] = this.data.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Data {
  String id;
  String menuCode;
  String restaurantId;
  String langId;
  String referenceKey;
  String menuName;
  String menuCategory;
  String menuType;
  String menuCuisine;
  String menuPrice;
  String menuAddons;
  String menuSplInstruction;
  String menuDescription;
  String menuPhoto;
  String menuPopularDish;
  String menuSpicy;
  String menuSpicyVal;
  String sizeoption;
  String pizzaSizeSmall;
  String pizzaSmallValue;
  String pizzaSizeMedium;
  String pizzaMediumValue;
  String pizzaSizeLarge;
  String pizzaLargeValue;
  String status;
  String deleteStatus;
  String addeddate;
  String menuNut;
  String menuNutVal;
  String menuHot;
  String menuGluten;
  String isCateringMenu;
  String menuAllergic;
  String menuDiscount;
  String menuDiscountType;
  String menuDiscountFrom;
  String menuDiscountTo;
  String menuAvailableDays;
  String orderBy;
  Null menuTaxType;
  Null menuTax;
  String pizza;
  String pizzaHalfHalf;
  Null pizzaToppings;
  Null pizzaCrust;
  Null pizzaHalfHalfPrice;
  String enableCrust;
  String inklTaxId;
  String modifiedDate;

  Data(
      {this.id,
      this.menuCode,
      this.restaurantId,
      this.langId,
      this.referenceKey,
      this.menuName,
      this.menuCategory,
      this.menuType,
      this.menuCuisine,
      this.menuPrice,
      this.menuAddons,
      this.menuSplInstruction,
      this.menuDescription,
      this.menuPhoto,
      this.menuPopularDish,
      this.menuSpicy,
      this.menuSpicyVal,
      this.sizeoption,
      this.pizzaSizeSmall,
      this.pizzaSmallValue,
      this.pizzaSizeMedium,
      this.pizzaMediumValue,
      this.pizzaSizeLarge,
      this.pizzaLargeValue,
      this.status,
      this.deleteStatus,
      this.addeddate,
      this.menuNut,
      this.menuNutVal,
      this.menuHot,
      this.menuGluten,
      this.isCateringMenu,
      this.menuAllergic,
      this.menuDiscount,
      this.menuDiscountType,
      this.menuDiscountFrom,
      this.menuDiscountTo,
      this.menuAvailableDays,
      this.orderBy,
      this.menuTaxType,
      this.menuTax,
      this.pizza,
      this.pizzaHalfHalf,
      this.pizzaToppings,
      this.pizzaCrust,
      this.pizzaHalfHalfPrice,
      this.enableCrust,
      this.inklTaxId,
      this.modifiedDate});

  Data.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    menuCode = json['menu_code'];
    restaurantId = json['restaurant_id'];
    langId = json['lang_id'];
    referenceKey = json['reference_key'];
    menuName = json['menu_name'];
    menuCategory = json['menu_category'];
    menuType = json['menu_type'];
    menuCuisine = json['menu_cuisine'];
    menuPrice = json['menu_price'];
    menuAddons = json['menu_addons'];
    menuSplInstruction = json['menu_spl_instruction'];
    menuDescription = json['menu_description'];
    menuPhoto = json['menu_photo'];
    menuPopularDish = json['menu_popular_dish'];
    menuSpicy = json['menu_spicy'];
    menuSpicyVal = json['menu_spicy_val'];
    sizeoption = json['sizeoption'];
    pizzaSizeSmall = json['pizza_size_small'];
    pizzaSmallValue = json['pizza_small_value'];
    pizzaSizeMedium = json['pizza_size_medium'];
    pizzaMediumValue = json['pizza_medium_value'];
    pizzaSizeLarge = json['pizza_size_large'];
    pizzaLargeValue = json['pizza_large_value'];
    status = json['status'];
    deleteStatus = json['delete_status'];
    addeddate = json['addeddate'];
    menuNut = json['menu_nut'];
    menuNutVal = json['menu_nut_val'];
    menuHot = json['menu_hot'];
    menuGluten = json['menu_gluten'];
    isCateringMenu = json['is_catering_menu'];
    menuAllergic = json['menu_allergic'];
    menuDiscount = json['menu_discount'];
    menuDiscountType = json['menu_discount_type'];
    menuDiscountFrom = json['menu_discount_from'];
    menuDiscountTo = json['menu_discount_to'];
    menuAvailableDays = json['menu_available_days'];
    orderBy = json['order_by'];
    menuTaxType = json['menu_tax_type'];
    menuTax = json['menu_tax'];
    pizza = json['Pizza'];
    pizzaHalfHalf = json['PizzaHalfHalf'];
    pizzaToppings = json['PizzaToppings'];
    pizzaCrust = json['PizzaCrust'];
    pizzaHalfHalfPrice = json['PizzaHalfHalfPrice'];
    enableCrust = json['enableCrust'];
    inklTaxId = json['inkl_tax_id'];
    modifiedDate = json['modified_date'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['menu_code'] = this.menuCode;
    data['restaurant_id'] = this.restaurantId;
    data['lang_id'] = this.langId;
    data['reference_key'] = this.referenceKey;
    data['menu_name'] = this.menuName;
    data['menu_category'] = this.menuCategory;
    data['menu_type'] = this.menuType;
    data['menu_cuisine'] = this.menuCuisine;
    data['menu_price'] = this.menuPrice;
    data['menu_addons'] = this.menuAddons;
    data['menu_spl_instruction'] = this.menuSplInstruction;
    data['menu_description'] = this.menuDescription;
    data['menu_photo'] = this.menuPhoto;
    data['menu_popular_dish'] = this.menuPopularDish;
    data['menu_spicy'] = this.menuSpicy;
    data['menu_spicy_val'] = this.menuSpicyVal;
    data['sizeoption'] = this.sizeoption;
    data['pizza_size_small'] = this.pizzaSizeSmall;
    data['pizza_small_value'] = this.pizzaSmallValue;
    data['pizza_size_medium'] = this.pizzaSizeMedium;
    data['pizza_medium_value'] = this.pizzaMediumValue;
    data['pizza_size_large'] = this.pizzaSizeLarge;
    data['pizza_large_value'] = this.pizzaLargeValue;
    data['status'] = this.status;
    data['delete_status'] = this.deleteStatus;
    data['addeddate'] = this.addeddate;
    data['menu_nut'] = this.menuNut;
    data['menu_nut_val'] = this.menuNutVal;
    data['menu_hot'] = this.menuHot;
    data['menu_gluten'] = this.menuGluten;
    data['is_catering_menu'] = this.isCateringMenu;
    data['menu_allergic'] = this.menuAllergic;
    data['menu_discount'] = this.menuDiscount;
    data['menu_discount_type'] = this.menuDiscountType;
    data['menu_discount_from'] = this.menuDiscountFrom;
    data['menu_discount_to'] = this.menuDiscountTo;
    data['menu_available_days'] = this.menuAvailableDays;
    data['order_by'] = this.orderBy;
    data['menu_tax_type'] = this.menuTaxType;
    data['menu_tax'] = this.menuTax;
    data['Pizza'] = this.pizza;
    data['PizzaHalfHalf'] = this.pizzaHalfHalf;
    data['PizzaToppings'] = this.pizzaToppings;
    data['PizzaCrust'] = this.pizzaCrust;
    data['PizzaHalfHalfPrice'] = this.pizzaHalfHalfPrice;
    data['enableCrust'] = this.enableCrust;
    data['inkl_tax_id'] = this.inklTaxId;
    data['modified_date'] = this.modifiedDate;
    return data;
  }
}